# Logistic Regression Baseline
* assume data has already been cleaned

## To Do:
- run classifier
- return metrics
- consolidate code into methods so it can be called on multiple datasets

In [84]:
import pandas as pd
import numpy as np
import string
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.model_selection import GridSearchCV, PredefinedSplit
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV # CV is cross validation
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score
from sklearn import svm

In [93]:
import urllib.request
import os.path

year='2014'

if not os.path.exists('data/processed/yelp_'+year+'_train.csv'):
    train = urllib.request.urlretrieve ('https://www.cs.mcgill.ca/~glluch/yelp_'+year+'/yelp_'+year+'_train.csv', 'data/processed/yelp_'+year+'_train.csv')
else:
    train = urllib.request.urlretrieve('file://'+os.path.abspath('data/processed/yelp_'+year+'_train.csv'))
    
if not os.path.exists('data/processed/yelp_'+year+'_dev.csv'):
    valid = urllib.request.urlretrieve ('https://www.cs.mcgill.ca/~glluch/yelp_'+year+'/yelp_'+year+'_dev.csv', 'data/processed/yelp_'+year+'_dev.csv')
else:
    valid = urllib.request.urlretrieve('file://'+os.path.abspath('data/processed/yelp_'+year+'_dev.csv'))
    
if not os.path.exists('data/processed/yelp_'+year+'_test.csv'):
    test = urllib.request.urlretrieve ('https://www.cs.mcgill.ca/~glluch/yelp_'+year+'/yelp_'+year+'_test.csv', 'data/processed/yelp_'+year+'_test.csv')
else:
    test = urllib.request.urlretrieve('file://'+os.path.abspath('data/processed/yelp_'+year+'_test.csv'))

In [94]:
train

('/home/edward/Documents/projects/aml-final/data/processed/yelp_2014_train.csv',
 <email.message.Message at 0x7fec6583e080>)

In [95]:
#load data
train = pd.read_csv(train[0])
test = pd.read_csv(test[0])
valid = pd.read_csv(valid[0])

X_train = train['text']
y_train = train['rating']
X_test = test['text']
y_test= test['rating']
X_valid = valid['text']
y_valid = valid['rating']

In [96]:
max_vocab = 50000
tf_idf = False
n=5
bow_transformer = CountVectorizer(max_features=max_vocab, ngram_range=(1,n), binary=True).fit(X_train.values.astype('U'))

MemoryError: 

In [ ]:
train = []
valid = []
test = []

X_train = bow_transformer.transform(X_train.values.astype('U'))
X_valid = bow_transformer.transform(X_valid.values.astype('U'))
X_test = bow_transformer.transform(X_test.values.astype('U'))

In [ ]:
if tf_idf:
    tf_transformer = TfidfTransformer(use_idf=False, smooth_idf=False, norm='l1') # check settings
    X_train = tf_transformer.fit_transform(X_train)
    X_valid = tf_transformer.transform(X_valid)
    X_test = tf_transformer.transform(X_test)

In [75]:
def logReg(X_train, y_train, X_test, y_test, cv=5):
    logreg = LogisticRegressionCV(cv=cv, multi_class='multinomial').fit(X_train, y_train)
    y_hat=lr.predict(X_test)

    print(confusion_matrix(y_test, y_hat))
    print('\n')
    print(classification_report(y_test, y_hat))

    print(accuracy_score(y_test, y_hat))
    return logreg.get_params()

In [71]:
#BoW
k=logReg(X_train,y_train, X_test, y_test)

ValueError: could not convert string to float: 'place good 5 years ago worst valley chips bad came table looked double fried full grease asked server fresh ones said fry chips morning said warm took chips picking put fryer gross yuk salsa old setting table got every table one started fermenting real lack caring anymore sad oh sad wo nt every back'

In [24]:
#BoW+TFIDF

/home/edward/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:757: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/home/edward/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:757: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/home/edward/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:757: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/home/edward/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:757: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/home/edward/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:757: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of

[[1973  470  127  140  149]
 [ 579 1064  726  439  156]
 [ 195  481 1568 2122  394]
 [ 112  138  770 6653 3309]
 [ 116   38  122 3122 8541]]


              precision    recall  f1-score   support

           1       0.66      0.69      0.68      2859
           2       0.49      0.36      0.41      2964
           3       0.47      0.33      0.39      4760
           4       0.53      0.61      0.57     10982
           5       0.68      0.72      0.70     11939

   micro avg       0.59      0.59      0.59     33504
   macro avg       0.57      0.54      0.55     33504
weighted avg       0.58      0.59      0.58     33504

0.590944364851958


/home/edward/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:757: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
